In [1]:
#libraries
import numpy as np
import pandas as pd
import matplotlib as plt

In [4]:
#to display all columns of dataset
pd.pandas.set_option('display.max_columns',None)

In [6]:
#import dataset
dataset = pd.read_csv("C:\\Users\\santy\\Desktop\\Krish Naik DS\\ANN\\Complete-Deep-Learning-master\\Complete-Deep-Learning-master\\ANN\\Churn_Modelling.csv")

In [8]:
#exited is the target variable/dependent feature
#columns rownumber and surname are non-essential 
dataset.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [9]:
x = dataset.iloc[:,3:13]
y = dataset.iloc[:,13]

In [12]:
x.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10

In [13]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [14]:
#creating dummy variables for Geography and Gender
geography = pd.get_dummies(x['Geography'], drop_first=True)
gender = pd.get_dummies(x['Gender'], drop_first=True)

In [16]:
#concantenate
x = pd.concat([x,geography,gender],axis=1)

In [17]:
#drop old categorical columns
x=x.drop(['Geography','Gender'], axis=1)

In [18]:
x.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Germany,Spain,Male
0,619,42,2,0.00,1,1,1,101348.88,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,1,0

In [19]:
#split into train and test data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state= 0)

In [20]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [23]:
#importing keras libraries
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LeakyReLU,PReLU,ELU
from keras.layers import Dropout

In [25]:
#initialising the ANN
classifier = Sequential()

In [27]:
#adding first input layer and first hidden layer
#units is the output dimensions, input_dim is no of input features
classifier.add(Dense(units=6, kernel_initializer='he_uniform', activation='relu', input_dim=11))

In [28]:
#adding second hidden layer
classifier.add(Dense(units=6, kernel_initializer='he_uniform', activation='relu'))

In [29]:
#adding output layer
classifier.add(Dense(units=1, kernel_initializer='glorot_uniform', activation = 'sigmoid'))

In [30]:
classifier.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 6)                 72
_________________________________________________________________
dense_1 (Dense)              (None, 6)                 42
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 7
=================================================================
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________

In [32]:
#compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [34]:
#fitting the ANN to training dataset
model_history = classifier.fit(x_train, y_train, validation_split=0.33, batch_size=10, epochs=100)

Epoch 1/100
536/536 [==============================] - 2s 3ms/step - loss: 0.5561 - accuracy: 0.7389 - val_loss: 0.4806 - val_accuracy: 0.7834
Epoch 2/100
536/536 [==============================] - 1s 3ms/step - loss: 0.4542 - accuracy: 0.8024 - val_loss: 0.4560 - val_accuracy: 0.7910
Epoch 3/100
536/536 [==============================] - 2s 3ms/step - loss: 0.4348 - accuracy: 0.8091 - val_loss: 0.4452 - val_accuracy: 0.7970
Epoch 4/100
536/536 [==============================] - 2s 3ms/step - loss: 0.4229 - accuracy: 0.8155 - val_loss: 0.4376 - val_accuracy: 0.8023
Epoch 5/100
536/536 [==============================] - 2s 3ms/step - loss: 0.4145 - accuracy: 0.8253 - val_loss: 0.4300 - val_accuracy: 0.8073
Epoch 6/100
536/536 [==============================] - 2s 3ms/step - loss: 0.4044 - accuracy: 0.8298 - val_loss: 0.4214 - val_accuracy: 0.8141
Epoch 7/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3923 - accuracy: 0.8406 - val_loss: 0.4090 - val_accuracy: 0.8228
Epoch 8/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3808 - accuracy: 0.8453 - val_loss: 0.3972 - val_accuracy: 0.8289
Epoch 9/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3701 - accuracy: 0.8526 - val_loss: 0.3879 - val_accuracy: 0.8311
Epoch 10/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3611 - accuracy: 0.8541 - val_loss: 0.3783 - val_accuracy: 0.8398
Epoch 11/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3541 - accuracy: 0.8552 - val_loss: 0.3731 - val_accuracy: 0.8402
Epoch 12/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3497 - accuracy: 0.8589 - val_loss: 0.3700 - val_accuracy: 0.8417
Epoch 13/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3459 - accuracy: 0.8578 - val_loss: 0.3678 - val_accuracy: 0.8406
Epoch 14/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3429 - accuracy: 0.8604 - val_loss: 0.3683 - val_accuracy: 0.8425
Epoch 15/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3412 - accuracy: 0.8600 - val_loss: 0.3650 - val_accuracy: 0.8470
Epoch 16/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3396 - accuracy: 0.8627 - val_loss: 0.3650 - val_accuracy: 0.8444
Epoch 17/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3385 - accuracy: 0.8623 - val_loss: 0.3633 - val_accuracy: 0.8455
Epoch 18/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3376 - accuracy: 0.8619 - val_loss: 0.3630 - val_accuracy: 0.8455
Epoch 19/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3364 - accuracy: 0.8634 - val_loss: 0.3633 - val_accuracy: 0.8466
Epoch 20/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3355 - accuracy: 0.8621 - val_loss: 0.3618 - val_accuracy: 0.8463
Epoch 21/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3349 - accuracy: 0.8636 - val_loss: 0.3620 - val_accuracy: 0.8466
Epoch 22/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3345 - accuracy: 0.8615 - val_loss: 0.3605 - val_accuracy: 0.8485
Epoch 23/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3337 - accuracy: 0.8632 - val_loss: 0.3605 - val_accuracy: 0.8489
Epoch 24/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3332 - accuracy: 0.8630 - val_loss: 0.3596 - val_accuracy: 0.8466
Epoch 25/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3326 - accuracy: 0.8649 - val_loss: 0.3588 - val_accuracy: 0.8474
Epoch 26/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3327 - accuracy: 0.8645 - val_loss: 0.3587 - val_accuracy: 0.8497
Epoch 27/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3320 - accuracy: 0.8642 - val_loss: 0.3597 - val_accuracy: 0.8501
Epoch 28/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3314 - accuracy: 0.8638 - val_loss: 0.3592 - val_accuracy: 0.8482
Epoch 29/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3315 - accuracy: 0.8636 - val_loss: 0.3581 - val_accuracy: 0.8519
Epoch 30/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3311 - accuracy: 0.8642 - val_loss: 0.3592 - val_accuracy: 0.8519
Epoch 31/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3310 - accuracy: 0.8664 - val_loss: 0.3584 - val_accuracy: 0.8516
Epoch 32/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3309 - accuracy: 0.8627 - val_loss: 0.3576 - val_accuracy: 0.8493
Epoch 33/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3301 - accuracy: 0.8647 - val_loss: 0.3574 - val_accuracy: 0.8519
Epoch 34/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3302 - accuracy: 0.8642 - val_loss: 0.3583 - val_accuracy: 0.8527
Epoch 35/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3298 - accuracy: 0.8640 - val_loss: 0.3577 - val_accuracy: 0.8531
Epoch 36/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3302 - accuracy: 0.8628 - val_loss: 0.3570 - val_accuracy: 0.8501
Epoch 37/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3300 - accuracy: 0.8642 - val_loss: 0.3570 - val_accuracy: 0.8516
Epoch 38/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3293 - accuracy: 0.8655 - val_loss: 0.3572 - val_accuracy: 0.8519
Epoch 39/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3294 - accuracy: 0.8668 - val_loss: 0.3575 - val_accuracy: 0.8516
Epoch 40/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3292 - accuracy: 0.8645 - val_loss: 0.3580 - val_accuracy: 0.8519
Epoch 41/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3292 - accuracy: 0.8643 - val_loss: 0.3568 - val_accuracy: 0.8508
Epoch 42/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3289 - accuracy: 0.8638 - val_loss: 0.3565 - val_accuracy: 0.8523
Epoch 43/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3289 - accuracy: 0.8645 - val_loss: 0.3580 - val_accuracy: 0.8497
Epoch 44/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3289 - accuracy: 0.8642 - val_loss: 0.3567 - val_accuracy: 0.8516
Epoch 45/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3284 - accuracy: 0.8630 - val_loss: 0.3566 - val_accuracy: 0.8512
Epoch 46/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3286 - accuracy: 0.8664 - val_loss: 0.3567 - val_accuracy: 0.8504
Epoch 47/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3288 - accuracy: 0.8651 - val_loss: 0.3560 - val_accuracy: 0.8527
Epoch 48/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3284 - accuracy: 0.8651 - val_loss: 0.3562 - val_accuracy: 0.8512
Epoch 49/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3279 - accuracy: 0.8628 - val_loss: 0.3577 - val_accuracy: 0.8497
Epoch 50/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3279 - accuracy: 0.8632 - val_loss: 0.3570 - val_accuracy: 0.8523
Epoch 51/100
536/536 [==============================] - 1s 3ms/step - loss: 0.3281 - accuracy: 0.8645 - val_loss: 0.3562 - val_accuracy: 0.8504
Epoch 52/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3278 - accuracy: 0.8630 - val_loss: 0.3563 - val_accuracy: 0.8531
Epoch 53/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3275 - accuracy: 0.8625 - val_loss: 0.3566 - val_accuracy: 0.8523
Epoch 54/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3273 - accuracy: 0.8643 - val_loss: 0.3588 - val_accuracy: 0.8516
Epoch 55/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3269 - accuracy: 0.8643 - val_loss: 0.3562 - val_accuracy: 0.8535
Epoch 56/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3270 - accuracy: 0.8638 - val_loss: 0.3570 - val_accuracy: 0.8527
Epoch 57/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3269 - accuracy: 0.8658 - val_loss: 0.3562 - val_accuracy: 0.8527

Epoch 58/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3270 - accuracy: 0.8640 - val_loss: 0.3562 - val_accuracy: 0.8531
Epoch 59/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3267 - accuracy: 0.8656 - val_loss: 0.3566 - val_accuracy: 0.8516
Epoch 60/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3268 - accuracy: 0.8634 - val_loss: 0.3563 - val_accuracy: 0.8531
Epoch 61/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3264 - accuracy: 0.8649 - val_loss: 0.3555 - val_accuracy: 0.8523
Epoch 62/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3265 - accuracy: 0.8660 - val_loss: 0.3560 - val_accuracy: 0.8542
Epoch 63/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3265 - accuracy: 0.8634 - val_loss: 0.3556 - val_accuracy: 0.8546
Epoch 64/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3259 - accuracy: 0.8643 - val_loss: 0.3561 - val_accuracy: 0.8542
Epoch 65/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3262 - accuracy: 0.8628 - val_loss: 0.3563 - val_accuracy: 0.8512
Epoch 66/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3262 - accuracy: 0.8645 - val_loss: 0.3564 - val_accuracy: 0.8504
Epoch 67/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3261 - accuracy: 0.8649 - val_loss: 0.3557 - val_accuracy: 0.8523
Epoch 68/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3258 - accuracy: 0.8643 - val_loss: 0.3553 - val_accuracy: 0.8523
Epoch 69/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3255 - accuracy: 0.8638 - val_loss: 0.3564 - val_accuracy: 0.8523
Epoch 70/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3258 - accuracy: 0.8647 - val_loss: 0.3574 - val_accuracy: 0.8550
Epoch 71/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3260 - accuracy: 0.8671 - val_loss: 0.3552 - val_accuracy: 0.8542
Epoch 72/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3259 - accuracy: 0.8649 - val_loss: 0.3563 - val_accuracy: 0.8519
Epoch 73/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3257 - accuracy: 0.8668 - val_loss: 0.3549 - val_accuracy: 0.8535
Epoch 74/100
536/536 [==============================] - 1s 3ms/step - loss: 0.3258 - accuracy: 0.8638 - val_loss: 0.3555 - val_accuracy: 0.8542
Epoch 75/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3252 - accuracy: 0.8675 - val_loss: 0.3591 - val_accuracy: 0.8508
Epoch 76/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3256 - accuracy: 0.8649 - val_loss: 0.3581 - val_accuracy: 0.8542
Epoch 77/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3260 - accuracy: 0.8647 - val_loss: 0.3554 - val_accuracy: 0.8538
Epoch 78/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3257 - accuracy: 0.8655 - val_loss: 0.3560 - val_accuracy: 0.8531
Epoch 79/100
536/536 [==============================] - 1s 3ms/step - loss: 0.3256 - accuracy: 0.8656 - val_loss: 0.3555 - val_accuracy: 0.8512
Epoch 80/100
536/536 [==============================] - 1s 2ms/step - loss: 0.3253 - accuracy: 0.8658 - val_loss: 0.3560 - val_accuracy: 0.8523
Epoch 81/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3250 - accuracy: 0.8658 - val_loss: 0.3553 - val_accuracy: 0.8557
Epoch 82/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3255 - accuracy: 0.8651 - val_loss: 0.3563 - val_accuracy: 0.8512
Epoch 83/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3255 - accuracy: 0.8647 - val_loss: 0.3553 - val_accuracy: 0.8523
Epoch 84/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3254 - accuracy: 0.8649 - val_loss: 0.3552 - val_accuracy: 0.8550
Epoch 85/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3256 - accuracy: 0.8690 - val_loss: 0.3558 - val_accuracy: 0.8542
Epoch 86/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3256 - accuracy: 0.8660 - val_loss: 0.3557 - val_accuracy: 0.8535
Epoch 87/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3252 - accuracy: 0.8656 - val_loss: 0.3561 - val_accuracy: 0.8535
Epoch 88/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3250 - accuracy: 0.8668 - val_loss: 0.3583 - val_accuracy: 0.8535
Epoch 89/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3258 - accuracy: 0.8662 - val_loss: 0.3554 - val_accuracy: 0.8538
Epoch 90/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3248 - accuracy: 0.8660 - val_loss: 0.3558 - val_accuracy: 0.8557
Epoch 91/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3255 - accuracy: 0.8656 - val_loss: 0.3568 - val_accuracy: 0.8527
Epoch 92/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3251 - accuracy: 0.8662 - val_loss: 0.3560 - val_accuracy: 0.8516
Epoch 93/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3251 - accuracy: 0.8640 - val_loss: 0.3577 - val_accuracy: 0.8504
Epoch 94/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3255 - accuracy: 0.8660 - val_loss: 0.3549 - val_accuracy: 0.8531
Epoch 95/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3255 - accuracy: 0.8655 - val_loss: 0.3553 - val_accuracy: 0.8527
Epoch 96/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3251 - accuracy: 0.8673 - val_loss: 0.3554 - val_accuracy: 0.8538
Epoch 97/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3252 - accuracy: 0.8671 - val_loss: 0.3560 - val_accuracy: 0.8508
Epoch 98/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3248 - accuracy: 0.8649 - val_loss: 0.3548 - val_accuracy: 0.8519
Epoch 99/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3253 - accuracy: 0.8651 - val_loss: 0.3555 - val_accuracy: 0.8535
Epoch 100/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3249 - accuracy: 0.8660 - val_loss: 0.3548 - val_accuracy: 0.8542

In [35]:
#predicting the Test set results
y_pred = classifier.predict(x_test)
y_pred = (y_pred>0.5)

In [36]:
#confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

In [37]:
cm

array([[1518,   77],
       [ 198,  207]], dtype=int64)

In [38]:
#accuracy
from sklearn.metrics import accuracy_score
score = accuracy_score(y_pred, y_test)

In [39]:
score

0.8625